server:
  port: 9527

spring:
  application:
    name: springcloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

zuul:
# 忽略真实服务名
#  ignored-services: springcloud-dept
# 忽略所有(*)服务名 加个前缀
# prefix: url 前缀
  prefix: /sanyue
  ignored-services: "*"  # 所有真实的微服务
  routes:
    mydept.serviceId: springcloud-dept
    mydept.path: /mydept/**